variables:
  buildtag: master  # always test master here - change to a vXYZ branch when using

jobs:
  - template: conda-package-tools/linux_python3.7_azure_template.yml
    parameters:
      buildtag: ${buildtag}
  - template: conda-package-tools/osx_python3.7_azure_template.yml
    parameters:
      buildtag: ${buildtag}
