# this azure config is only for testing in the conda-package-tools repo
# see the readme for how to configure another repo
jobs:
  - template: linux_python3.8_azure_template.yml
    parameters:
      buildtag: $(Build.SourceBranchName)
  - template: osx_python3.8_azure_template.yml
    parameters:
      buildtag: $(Build.SourceBranchName)
