resources:
  repositories:
    - repository: templates
      type: github
      name: beckermr/conda-package-tools
      ref: enh-v2
      endpoint: azure-read-only

variables:
  buildtag: $(Build.SourceBranchName)

jobs:
  - template: linux_python3.7_azure_template.yml@templates
    parameters:
      buildtag: ${buildtag}
  - template: osx_python3.7_azure_template.yml@templates
    parameters:
      buildtag: ${buildtag}
