resources:
  repositories:
    - repository: templates
      type: github
      name: beckermr/conda-package-tools
      ref: refs/heads/master

variables:
  buildtag: master

jobs:
  - template: linux_python3.7_azure_template.yml@templates
    parameters:
      buildtag: ${buildtag}
  - template: osx_python3.7_azure_template.yml@templates
    parameters:
      buildtag: ${buildtag}
