# this azure config is only for testing in the conda-package-tools repo
# see the readme for how to configure another repo
variables:
  buildtag: $(Build.SourceBranchName)

jobs:
  - template: linux_python3.7_azure_template.yml
    parameters:
      buildtag: ${buildtag}
  - template: osx_python3.7_azure_template.yml
    parameters:
      buildtag: ${buildtag}
