parameters:
  buildtag: 'v999999999999999'  # does not exist so should error

jobs:
- job: linux_python38
  pool:
    vmImage: 'Ubuntu-16.04'
  timeoutInMinutes: 360
  steps:
  - checkout: self
    clean: true
  - bash: |
        sudo apt-get remove -y --auto-remove gcc
        sudo apt-get purge -y --auto-remove gcc
        sed -h
        echo `uname -s`
    displayName:
      removing system compilers
  - bash: |
      echo "using branch/tag '${BUILDTAG}' of conda-package-tools"
      if [ "$BUILD_REPOSITORY_NAME" != "beckermr/conda-package-tools" ]; then
          git clone -b ${BUILDTAG} https://github.com/beckermr/conda-package-tools.git
      fi
    displayName:
      bootstrap
    env:
      BUILDTAG: ${{ parameters.buildtag }}
  - bash: ./conda-package-tools/install_miniconda.sh
    displayName: install miniconda
    env:
      CONFIG: 'linux_python3.8'
  - bash: ./conda-package-tools/build.sh
    displayName: build and upload package
    env:
      CONFIG: 'linux_python3.8'
      ANACONDA_TOKEN: $(anaconda.token)
