parameters:
  buildtag: 'v999999999999999'  # does not exist so should error

jobs:
- job: osx_python37
  pool:
    vmImage: 'macOS-10.13'
  timeoutInMinutes: 360
  steps:
  - checkout: self
    clean: true
  - bash: |
      sudo chown -R $USER $CONDA  # not actually needed but here for later
      sudo chown -R $USER $HOME/.conda
    displayName:
      Fix conda directory permissions.
  - bash: |
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew
    displayName:
      remove homebrew
  - bash: |
      echo "using branch/tag '${BUILDTAG}' of conda-package-tools"
      if [ "$BUILD_REPOSITORY_NAME" != "beckermr/conda-package-tools" ]; then
          git clone -b ${BUILDTAG} https://github.com/beckermr/conda-package-tools.git
      fi
    displayName:
      bootstrap
    env:
      BUILDTAG: ${{ parameters.buildtag }}
  - bash: ./conda-package-tools/install_miniconda.sh
    displayName: install miniconda
    env:
      CONFIG: 'osx_python3.7'
  - bash: ./conda-package-tools/build.sh
    displayName: build and upload package
    env:
      CONFIG: 'osx_python3.7'
      ANACONDA_TOKEN: $(anaconda.token)
